"""empty message

Revision ID: a52b53d22aee
Revises: 536917e3b9c2
Create Date: 2019-12-04 16:10:24.810106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a52b53d22aee'
down_revision = '536917e3b9c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Searched_queries', sa.Column('query', sa.String(), nullable=False))
    op.drop_column('Searched_queries', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Searched_queries', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('Searched_queries', 'query')
    # ### end Alembic commands ###
