"""empty message

Revision ID: ae9e7d74b955
Revises: a52b53d22aee
Create Date: 2019-12-04 16:14:07.476774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae9e7d74b955'
down_revision = 'a52b53d22aee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Searched_queries', sa.Column('query_name', sa.String(), nullable=False))
    op.drop_column('Searched_queries', 'query')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Searched_queries', sa.Column('query', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('Searched_queries', 'query_name')
    # ### end Alembic commands ###
